### ISSUE TITLE
Incompatible with Version 6.0.1 (6A317)

### ISSUE THREAD

**Issue by SpottedRabbit** [wczekalski/WCGitTagsPlugin#2]
I am unable to get the plugin to work with the newest version of Xcode, it seems to install but then disappears upon restart of Xcode

**Comment by SpottedRabbit** [comment]
I have created a fork that fixes the Xcode 6 problem. I also fixed a bug that never activated the add tag button. Give it a try and let me know if it works for you.

**Comment by SpottedRabbit** [comment]
Sorry...if you plan to run in debug mode in Xcode , you have to turn off the UI debugging feature in the scheme. Otherwise, it will crash on launch...
![untitled](https://cloud.githubusercontent.com/assets/6156289/5592740/167b90ba-91d8-11e4-8584-fdcfe7654213.png)

**Comment by wczekalski** [comment]
Please open a pull request

**Comment by SpottedRabbit** [comment]
Done. The fix I added to enable the the add button was a bit brute force as the add button will now always be enabled. I just realised a better way to fix it, but it will take a bit more work. Sorry about this. Happy to have you not accept the pull request until I figure out a better way.

**Comment by SpottedRabbit** [comment]
OK...made some more improvements in my pull request. Hope you like them.

**Comment by wczekalski** [comment]
Fixed #3
